apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: bandwidth-test
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: <XX-REPLACE-XX>
              imagePullPolicy: Always
              name: bandwidth-test-launcher
              env:
                - name: LD_LIBRARY_PATH
                  value: /opt/aws/neuron/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:$LD_LIBRARY_PATH
                - name: PATH
                  value: $PATH:/opt/aws/neuron/bin:/opt/amazon/efa/bin:/opt/amazon/openmpi/bin:/usr/sbin:/usr/bin:/usr/local/bin
                - name: CCOM_SOCKET_IFNAME
                  value: eth0
                - name: NEURON_RT_ROOT_COMM_ID
                  value: bandwidth-test-worker-0:61001
                - name: FI_EFA_FORK_SAFE
                  value: '1'
              command: [
                  'mpirun',
                  '--allow-run-as-root',
                  '-n',
                  '2',
                  '-bind-to',
                  'none',
                  '-map-by',
                  'slot',
                  '-x',
                  'LD_LIBRARY_PATH',
                  '-x',
                  'PATH',
                  '-x',
                  'CCOM_SOCKET_IFNAME',
                  '-x',
                  'NEURON_RT_ROOT_COMM_ID',
                  '-x',
                  'FI_EFA_FORK_SAFE',
                  # '-mca',
                  # 'pml',
                  # 'ob1',
                  # '-mca',
                  # 'btl',
                  # '^openib',
                  # '--oversubscribe',
                  # command
                  '/opt/aws/neuron/bin/nccom-test',
                  '--script-mode',
                  '--nworkers',
                  '32',
                  '--nnodes',
                  '2',
                  '--minbytes',
                  '8',
                  '--maxbytes',
                  '1G',
                  '--stepfactor',
                  '2',
                  '--iters',
                  '3',
                  '--warmup_iters',
                  '3',
                  '--datatype',
                  'fp32',
                  'all_reduce',
                  '--hosts',
                  'bandwidth-test-worker-0',
                  'bandwidth-test-worker-1',
                ]
    Worker:
      replicas: 2
      template:
        spec:
          tolerations:
            - key: 'aws.amazon.com/neuron'
              operator: 'Exists'
              effect: 'NoSchedule'
          containers:
            - image: <XX-REPLACE-XX>
              imagePullPolicy: Always
              name: bandwidth-test
              securityContext:
                privileged: true
              resources:
                limits:
                  aws.amazon.com/neuron: '16'
                  hugepages-2Mi: 5120Mi
                  memory: 12G
                requests:
                  aws.amazon.com/neuron: '16'
                  hugepages-2Mi: 5120Mi
                  memory: 12G
