apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: bandwidth-test
spec:
  slotsPerWorker: 16
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          tolerations:
            - key: 'aws.amazon.com/neuron'
              operator: 'Exists'
              effect: 'NoSchedule'
          containers:
            - image: <REPLACE>
              name: bandwidth-test-launcher
              env:
                - name: LD_LIBRARY_PATH
                  value: /opt/aws/neuron/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:$LD_LIBRARY_PATH
                - name: PATH
                  value: $PATH:/opt/aws/neuron/bin:/opt/amazon/efa/bin:/opt/amazon/openmpi/bin:/usr/sbin:/usr/bin:/usr/local/bin
                - name: CCOM_SOCKET_IFNAME÷
                  value: eth0
                - name: NEURON_RT_ROOT_COMM_ID
                  value: bandwidth-test-worker-0:61001
              command: [
                  'mpirun',
                  '--allow-run-as-root',
                  '--tag-output',
                  '-n',
                  '16',
                  '-bind-to',
                  'none',
                  '-map-by',
                  'slot',
                  '-x',
                  'LD_LIBRARY_PATH',
                  '-x',
                  'PATH',
                  '-x',
                  'CCOM_SOCKET_IFNAME',
                  '-x',
                  'NEURON_RT_ROOT_COMM_ID',
                  # '--mca',
                  # 'pml',
                  # '^cm',
                  # '--oversubscribe',
                  # command
                  '/opt/aws/neuron/bin/nccom-test',
                  # '--script-mode',
                  '--nworkers',
                  '64',
                  '--nnodes',
                  '2',
                  '--minbytes',
                  '500M',
                  '--maxbytes',
                  '2G',
                  '--stepfactor',
                  '2',
                  '--iters',
                  '10',
                  '--warmup_iters',
                  '5',
                  '--datatype',
                  'fp32',
                  'all_reduce',
                  '--hosts',
                  'bandwidth-test-worker-0',
                  'bandwidth-test-worker-1',
                ]
          initContainers:
            - image: <REPLACE>
              name: init
              command: ['sh', '-c', 'sleep 5']
    Worker:
      replicas: 2
      template:
        spec:
          tolerations:
            - key: 'aws.amazon.com/neuron'
              operator: 'Exists'
              effect: 'NoSchedule'
          containers:
            - image: <REPLACE>
              name: bandwidth-test
              resources:
                limits:
                  aws.amazon.com/neuron: 16
                requests:
                  aws.amazon.com/neuron: 16
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
